# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Set up node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com/open-game-backend/'
        # Required to apply registry-url: https://github.com/actions/setup-node/issues/73
        scope: '@open-game-backend'

    - name: Install dependencies
      run: npm ci

    - name: Build package
      run: npm run build --if-present

    - name: Test package
      run: npm test

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: dist

    - name: Publish package 
      run: |
        npm config set scope "@open-game-backend"
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
